"""Add Trainee Management

Revision ID: 137cc10fab91
Revises: 992a33945814
Create Date: 2026-09-12 21:10:17.606625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '137cc10fab91'
down_revision: Union[str, None] = '992a33945814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('personnel', sa.Column('is_trainee', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('personnel', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_personnel_course_id'), 'personnel', ['course_id'], unique=False)
    
    # Use batch_alter_table for SQLite compatibility when adding foreign keys
    with op.batch_alter_table('personnel', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_personnel_course_id', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personnel', schema=None) as batch_op:
        batch_op.drop_constraint('fk_personnel_course_id', type_='foreignkey')
        
    op.drop_index(op.f('ix_personnel_course_id'), table_name='personnel')
    op.drop_column('personnel', 'course_id')
    op.drop_column('personnel', 'is_trainee')
    op.drop_table('courses')
    # ### end Alembic commands ###
