"""Initial migration

Revision ID: 992a33945814
Revises: 
Create Date: 2026-09-12 20:37:30.182347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '992a33945814'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('communication_password', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connection_status', sa.String(length=20), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holiday_date')
    )
    op.create_table('ranks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('late_grace_minutes', sa.Integer(), nullable=False),
    sa.Column('early_leave_minutes', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('attendance_punches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('biometric_user_id', sa.String(length=50), nullable=False),
    sa.Column('punch_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('punch_type', sa.String(length=10), nullable=True),
    sa.Column('verified', sa.Integer(), nullable=True),
    sa.Column('raw_status', sa.Integer(), nullable=True),
    sa.Column('raw_work_code', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'biometric_user_id', 'punch_time', name='uq_punch_identity')
    )
    op.create_index(op.f('ix_attendance_punches_biometric_user_id'), 'attendance_punches', ['biometric_user_id'], unique=False)
    op.create_index(op.f('ix_attendance_punches_device_id'), 'attendance_punches', ['device_id'], unique=False)
    op.create_index(op.f('ix_attendance_punches_punch_time'), 'attendance_punches', ['punch_time'], unique=False)
    op.create_table('device_sync_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('logs_found', sa.Integer(), nullable=False),
    sa.Column('logs_inserted', sa.Integer(), nullable=False),
    sa.Column('logs_skipped', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_sync_logs_device_id'), 'device_sync_logs', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_sync_logs_started_at'), 'device_sync_logs', ['started_at'], unique=False)
    op.create_table('personnel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('biometric_user_id', sa.String(length=50), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('rank_id', sa.Integer(), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('duty_type', sa.String(length=50), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('sanctioned_status', sa.String(length=50), nullable=True),
    sa.Column('employment_status', sa.String(length=20), nullable=False),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['rank_id'], ['ranks.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personnel_biometric_user_id'), 'personnel', ['biometric_user_id'], unique=True)
    op.create_index(op.f('ix_personnel_department_id'), 'personnel', ['department_id'], unique=False)
    op.create_index(op.f('ix_personnel_rank_id'), 'personnel', ['rank_id'], unique=False)
    op.create_table('attendance_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('first_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_work_minutes', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('late_minutes', sa.Integer(), nullable=False),
    sa.Column('overtime_minutes', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personnel_id', 'attendance_date', name='uq_daily_attendance')
    )
    op.create_index(op.f('ix_attendance_daily_attendance_date'), 'attendance_daily', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_daily_personnel_id'), 'attendance_daily', ['personnel_id'], unique=False)
    op.create_table('exceptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('exception_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exceptions_date'), 'exceptions', ['date'], unique=False)
    op.create_index(op.f('ix_exceptions_personnel_id'), 'exceptions', ['personnel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exceptions_personnel_id'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_date'), table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_attendance_daily_personnel_id'), table_name='attendance_daily')
    op.drop_index(op.f('ix_attendance_daily_attendance_date'), table_name='attendance_daily')
    op.drop_table('attendance_daily')
    op.drop_index(op.f('ix_personnel_rank_id'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_department_id'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_biometric_user_id'), table_name='personnel')
    op.drop_table('personnel')
    op.drop_index(op.f('ix_device_sync_logs_started_at'), table_name='device_sync_logs')
    op.drop_index(op.f('ix_device_sync_logs_device_id'), table_name='device_sync_logs')
    op.drop_table('device_sync_logs')
    op.drop_index(op.f('ix_attendance_punches_punch_time'), table_name='attendance_punches')
    op.drop_index(op.f('ix_attendance_punches_device_id'), table_name='attendance_punches')
    op.drop_index(op.f('ix_attendance_punches_biometric_user_id'), table_name='attendance_punches')
    op.drop_table('attendance_punches')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_table('shifts')
    op.drop_table('ranks')
    op.drop_table('holidays')
    op.drop_table('devices')
    op.drop_table('departments')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
