"""Add directory fields to personnel

Revision ID: b8fd22b7ba2b
Revises: fe739125c026
Create Date: 2026-09-12 21:59:14.837360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8fd22b7ba2b'
down_revision: Union[str, None] = 'fe739125c026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personnel', sa.Column('cnic', sa.String(length=20), nullable=True))
    op.add_column('personnel', sa.Column('father_name', sa.String(length=200), nullable=True))
    op.add_column('personnel', sa.Column('dob', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personnel', 'is_trainee',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.drop_column('personnel', 'dob')
    op.drop_column('personnel', 'father_name')
    op.drop_column('personnel', 'cnic')
    # ### end Alembic commands ###
