"""add_gender_to_personnel

Revision ID: fe739125c026
Revises: 137cc10fab91
Create Date: 2026-09-12 21:35:28.846230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe739125c026'
down_revision: Union[str, None] = '137cc10fab91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personnel', sa.Column('gender', sa.String(length=10), server_default='Male', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personnel', 'gender')
    # ### end Alembic commands ###
